In [2]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Functions ##

In [4]:
def say_hello(name):
    return 'hola ' + name

say_hello('Paul')

'hola Paul'

In [5]:
#Your turn: write a function triple that returns the triple of a given input
def triple(x):
    return 3*x

In [6]:
triple(9)

27

In [7]:
triple('hello')

'hellohellohello'

In [8]:
num = 4

In [9]:
triple(num)

12

### Note About Scopes

In [12]:
x

NameError: name 'x' is not defined

In [13]:
x = 5

In [15]:
triple(2 * x)

30

In [ ]:
x

### Type Agnostic

In [16]:
triple('ha')

'hahaha'

In [17]:
triple(np.arange(4))

array([0, 3, 6, 9])

### What this function do?

In [18]:
def percent_of_total(s):
    return np.round(s / sum(s) * 100, 2)

In [19]:
percent_of_total(make_array(1,1,1,1))

array([ 25.,  25.,  25.,  25.])

In [20]:
percent_of_total(make_array(1, 213, 38))

array([  0.4 ,  84.52,  15.08])

### Multiple Arguments

$ h^2 = x^2 + y^2 \hspace{20 pt} => \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $

In [21]:
def hypotenuse(x,y):
    hypot_squared = (x ** 2 + y ** 2)
    return hypot_squared ** 0.5

In [22]:
hypotenuse(9, 12)

15.0

In [23]:
hypotenuse(2, 2)

2.8284271247461903

In [24]:
hypotenuse(1)

TypeError: hypotenuse() missing 1 required positional argument: 'y'

In [ ]:
#Your turn: write a function called hello2 will do the following
#hello2('A','B')
#output: 'Hello A and B'
...

In [ ]:
hello2('A', 'B')

## Apply using function

In [26]:
student = Table().with_columns(
    'Name', make_array('Jim', 'Dwight', 'Michael', 'Creed'),
    'Birth Year', make_array(1985, 1988, 1967, 1904)
)
student

Name    | Birth Year
Jim     | 1985
Dwight  | 1988
Michael | 1967
Creed   | 1904

In [27]:
def greeting(person):
    return 'Bonjour ' + person

In [28]:
greeting('Karen')

'Bonjour Karen'

In [30]:
greeting('Carl')

'Bonjour Carl'

In [31]:
student.with_column('greeting',student.apply(greeting, 'Name'))

Name    | Birth Year | greeting
Jim     | 1985       | Bonjour Jim
Dwight  | 1988       | Bonjour Dwight
Michael | 1967       | Bonjour Michael
Creed   | 1904       | Bonjour Creed

In [32]:
def name_and_age(name, year):
    age = 2025 - year -1
    return name + ' is ' + str(age) + ' years old'

In [33]:
name_and_age('Thomas',2006)

'Thomas is 18 years old'

In [34]:
student2 = student.apply(name_and_age, 'Name','Birth Year')
student2

array(['Jim is 39 years old', 'Dwight is 36 years old',
       'Michael is 57 years old', 'Creed is 120 years old'],
      dtype='<U23')

In [ ]:
#Your turn: add an addtional column called Over35, if the stduent age in 2025 is over 35 then "Yes", other than "No"
#hint: write a function, then use apply
def if_over