In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
! pip install datascience

Collecting datascience
  Downloading datascience-0.18.0-py3-none-any.whl.metadata (910 bytes)
Requirement already satisfied: folium>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from datascience) (0.20.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from datascience) (75.2.0)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from datascience) (3.10.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datascience) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from datascience) (1.16.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from datascience) (2.0.2)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from datascience) (7.34.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from datascience) (5.24.1)
Requirement already satisfied: branca in /usr/local/lib/python3.12/dist-packages (from datascience) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from folium>=0.9.1->datascience) (3.1.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from folium>=0.9.1->datascience) (2.32.4)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from folium>=0.9.1->datascience) (2025.4.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->datascience) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->datascience) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->datascience) (4.60.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->datascience) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->datascience) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->datascience) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->datascience) (3.2.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->datascience) (2.9.0.post0)
Collecting jedi>=0.16 (from ipython->datascience)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->datascience) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->datascience) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->datascience) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->datascience) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->datascience) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->datascience) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->datascience) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->datascience) (4.9.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datascience) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datascience) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->datascience) (8.5.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->datascience) (0.8.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9->folium>=0.9.1->datascience) (3.0.2)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->datascience) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->datascience) (0.2.13)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->datascience) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->folium>=0.9.1->datascience) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->folium>=0.9.1->datascience) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->folium>=0.9.1->datascience) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->folium>=0.9.1->datascience) (2025.8.3)
Downloading datascience-0.18.0-py3-none-any.whl (725 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 725.0/725.0 kB 13.2 MB/s eta 0:00:00
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 40.7 MB/s eta 0:00:00
Installing collected packages: jedi, datascience
Successfully installed datascience-0.18.0 jedi-0.19.2

In [3]:
from datascience import *

In [4]:
tbl=Table.read_table('/content/drive/MyDrive/IS296_Colab/demo/week5/fitbit-sleep.csv')
tbl

Start Time          | End Time           | Minutes Asleep | Minutes Awake | Number of Awakenings | Time in Bed | Minutes REM Sleep | Minutes Light Sleep | Minutes Deep Sleep
2022-09-25 12:21 AM | 2022-09-25 8:56 AM | 472            | 43            | 21                   | 515         | 128               | 257                 | 87
2022-09-23 10:00 PM | 2022-09-24 7:55 AM | 549            | 46            | 25                   | 595         | 165               | 303                 | 81
2022-09-22 11:53 PM | 2022-09-23 6:08 AM | 339            | 36            | 22                   | 375         | 96                | 212                 | 31
2022-09-21 10:57 PM | 2022-09-22 5:35 AM | 358            | 40            | 19                   | 398         | 94                | 199                 | 65
2022-09-20 11:52 PM | 2022-09-21 6:08 AM | 350            | 26            | 12                   | 376         | 103               | 187                 | 60
2022-09-19 11:48 PM | 2022-09-20 6:06 AM | 340            | 38            | 16                   | 378         | 90                | 208                 | 42
2022-09-18 10:25 PM | 2022-09-19 5:36 AM | 395            | 35            | 23                   | 430         | 103               | 211                 | 81
2022-09-18 1:00 AM  | 2022-09-18 8:12 AM | 400            | 32            | 24                   | 432         | 153               | 164                 | 83
2022-09-16 11:32 PM | 2022-09-17 8:38 AM | 478            | 68            | 38                   | 546         | 115               | 288                 | 75
2022-09-16 12:16 AM | 2022-09-16 7:46 AM | 386            | 64            | 34                   | 450         | 77                | 280                 | 29
... (10 rows omitted)

In [8]:
REM_sleep=tbl.column('Minutes REM Sleep')
deep_sleep=tbl.column('Minutes Deep Sleep')
awake = tbl.column('Minutes Awake')
total_sleep = tbl.column('Minutes Asleep')

In [10]:
REM_percentage = REM_sleep/total_sleep * 100
REM_percentage

array([ 27.11864407,  30.05464481,  28.31858407,  26.25698324,
        29.42857143,  26.47058824,  26.07594937,  38.25      ,
        24.05857741,  19.94818653,  -1.17647059,  12.03703704,
        -1.36986301,  24.13793103,  -0.25445293,  25.51546392,
        36.74540682,  -0.26455026,  25.51319648,  22.25913621])

In [12]:
SQI = (REM_sleep/total_sleep*100)*.4 + (deep_sleep/total_sleep*100)*.4 + (1-awake/total_sleep)*100*0.2

In [11]:
import numpy as np

In [13]:
np.mean(SQI)

31.09941377810058

In [14]:
np.std(SQI)

7.678951962819494

In [15]:
np.max(SQI)

42.0

In [16]:
steps=Table.read_table('/content/drive/MyDrive/IS296_Colab/demo/week5/fitbit_excercise_2024.csv')
steps

Index | Date       | Day_of_Week | Calories Burned | Steps | Distance | Minutes Sedentary | Minutes Lightly Active | Minutes Fairly Active | Minutes Very Active | Activity Calories
1     | 2024-01-16 | Tue         | 1532            | 4604  | 1.92     | 774               | 215                    | 6                     | 1                   | 530
2     | 2024-01-17 | Wed         | 1476            | 4385  | 1.83     | 821               | 175                    | 6                     | 1                   | 452
3     | 2024-01-18 | Thur        | 1554            | 7766  | 3.24     | 833               | 136                    | 29                    | 18                  | 540
4     | 2024-01-19 | Fri         | 1515            | 5167  | 2.16     | 1,273             | 141                    | 7                     | 19                  | 471
5     | 2024-01-20 | Sat         | 1481            | 5399  | 2.26     | 875               | 155                    | 3                     | 18                  | 459
6     | 2024-01-21 | Sun         | 1423            | 4175  | 1.74     | 718               | 135                    | 0                     | 0                   | 357
7     | 2024-01-22 | Mon         | 1498            | 6711  | 2.8      | 841               | 118                    | 1                     | 37                  | 465
8     | 2024-01-23 | Tue         | 1588            | 8105  | 3.38     | 975               | 146                    | 14                    | 29                  | 565
9     | 2024-01-24 | Wed         | 1712            | 9542  | 3.99     | 864               | 190                    | 12                    | 34                  | 709
10    | 2024-01-25 | Thur        | 1667            | 8083  | 3.38     | 696               | 202                    | 4                     | 33                  | 678
... (21 rows omitted)

What was the average calories burned on all Mondays